USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_PROJECT;
USE SCHEMA STAGING;

-- GOAL OF THIS WORKSHEET IS SOME QUICK DQ CHECKS BEFORE NORMALIZING AND MOVING DATA IN THE CORE SCHEMA

-- CHECK FOR NULLS 
-- RESULT: ONLY 4 NULLS IN POSTAL_CODE, I WILL MAKE A DQ FLAG LATER TO CAPTURE THESE ROWS
SELECT 
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(ROW_ID IS NULL) AS NULL_ROW_ID,
    COUNT_IF(ORDER_ID IS NULL) AS NULL_ORDER_ID,
    COUNT_IF(ORDER_DATE IS NULL) AS NULL_ORDER_DATE,
    COUNT_IF(SHIP_DATE IS NULL) AS NULL_SHIP_DATE,
    COUNT_IF(SHIP_MODE IS NULL) AS NULL_SHIP_MODE,
    COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(CUSTOMER_NAME IS NULL) AS NULL_CUSTOMER_NAME,
    COUNT_IF(SEGMENT IS NULL) AS NULL_SEGMENT,
    COUNT_IF(COUNTRY IS NULL) AS NULL_COUNTRY,
    COUNT_IF(CITY IS NULL) AS NULL_CITY,
    COUNT_IF(STATE IS NULL) AS NULL_STATE,
    COUNT_IF(POSTAL_CODE IS NULL) AS NULL_POSTAL_CODE,
    COUNT_IF(REGION IS NULL) AS NULL_REGION,
    COUNT_IF(PRODUCT_ID IS NULL) AS NULL_PRODUCT_ID,
    COUNT_IF(CATEGORY IS NULL) AS NULL_CATEGORY,
    COUNT_IF(SUB_CATEGORY IS NULL) AS NULL_SUB_CATEGORY,
    COUNT_IF(PRODUCT_NAME IS NULL) AS NULL_PRODUCT_NAME,
    COUNT_IF(SALES IS NULL) AS NULL_SALES
FROM STG_SUPERSTORE_SALES;

-- OUTLIERS IN SALES, NO NEGATIVE VALUES, LOOKS GOOD
SELECT 
    MIN(SALES) AS MIN_SALES,
    MAX(SALES) AS MAX_SALES,
    AVG(SALES) AS AVG_SALES,
    STDDEV(SALES) AS STDDEV_SALES
FROM STG_SUPERSTORE_SALES;

-- 31 ROWS FOUND HERE, UPON SCANNING THESE ROWS, I DECIDED TO KEEP ALL
SELECT *
FROM STG_SUPERSTORE_SALES
WHERE SALES > (
    SELECT AVG(SALES) + 3 * STDDEV(SALES) FROM STG_SUPERSTORE_SALES
)
OR SALES < (
    SELECT AVG(SALES) - 3 * STDDEV(SALES) FROM STG_SUPERSTORE_SALES
);

-- DUPLICATE ORDER_ID
SELECT 
    ORDER_ID, 
    COUNT(*) AS COUNT_ORDER_ID
FROM STG_SUPERSTORE_SALES
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

-- INVESTIGATE AN EXAMPLE
-- UPON INVESTIGATION, I REALIZED CUSTOMERS WITH THE SAME ORDER ON THE SAME DAY CAN HAVE MULTIPLE ROWS IF THEIR ORDER INCLUDES MORE THAN ONE PRODUCT
SELECT * 
FROM STG_SUPERSTORE_SALES
WHERE ORDER_ID = 'CA-2017-152156';

-- SEE MAX LENGTH OF EACH COLUMN TO SAVE STORAGE WHILE MOVING THE DATA TO THE CORE SCHEMA
SELECT 
    MAX(LENGTH(TRIM(ORDER_ID))) AS MAX_ORDER_ID,
    MAX(LENGTH(TRIM(CUSTOMER_ID))) AS MAX_CUSTOMER_ID,
    MAX(LENGTH(TRIM(CUSTOMER_NAME))) AS MAX_CUSTOMER_NAME,
    MAX(LENGTH(TRIM(SEGMENT))) AS MAX_SEGMENT,
    MAX(LENGTH(TRIM(COUNTRY))) AS MAX_COUNTRY,
    MAX(LENGTH(TRIM(CITY))) AS MAX_CITY,
    MAX(LENGTH(TRIM(STATE))) AS MAX_STATE,
    MAX(LENGTH(TRIM(REGION))) AS MAX_REGION,
    MAX(LENGTH(TRIM(POSTAL_CODE))) AS MAX_POSTAL_CODE,
    MAX(LENGTH(TRIM(PRODUCT_ID))) AS MAX_PRODUCT_ID,
    MAX(LENGTH(TRIM(CATEGORY))) AS MAX_CATEGORY,
    MAX(LENGTH(TRIM(SUB_CATEGORY))) AS MAX_SUB_CATEGORY,
    MAX(LENGTH(TRIM(PRODUCT_NAME))) AS MAX_PRODUCT_NAME,
    MAX(LENGTH(TRIM(SALES))) AS MAX_SALES
FROM STG_SUPERSTORE_SALES;
